#!/bin/bash
read salary
if [ $salary < 10000 ]
then
echo "no tax for $salary"
if [ $salary > 10000 ] & [ $salary < 25000 ]
then
echo "5% tax included for $salary"
if [ $salary > 25000 ]
then 
echo "10% tax included for $salary"
fi
fi
fi
